<?php

use function VSGutenberg\Helpers\simple_slug;

function get_flex_alignment_rules($group_name = 'Flex Alignment') {

    $group_label = $group_name;
    $group_slug = simple_slug($group_name);
    $group_key = 'field_' . $group_slug;
    return array(
        'key' => $group_key,
        'label' => $group_label,
        'name' => $group_slug,
        'aria-label' => '',
        'type' => 'group',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'layout' => 'block',
        'sub_fields' => array(
            array(
                'key' => 'field_687e71bc31999',
                'label' => 'Wrap',
                'name' => 'wrap',
                'aria-label' => '',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'table',
                'sub_fields' => array(
                    array(
                        'key' => 'field_687e71bc3199a',
                        'label' => 'Desktop',
                        'name' => 'desktop',
                        'aria-label' => '',
                        'type' => 'button_group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'wrap' => 'wrap',
                            'nowrap' => 'nowrap',
                        ),
                        'default_value' => 'wrap',
                        'return_format' => 'value',
                        'allow_null' => 0,
                        'layout' => 'vertical',
                    ),
                    array(
                        'key' => 'field_687e71bc3199b',
                        'label' => 'Tablet',
                        'name' => 'tablet',
                        'aria-label' => '',
                        'type' => 'button_group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'wrap' => 'wrap',
                            'nowrap' => 'nowrap',
                        ),
                        'default_value' => 'wrap',
                        'return_format' => 'value',
                        'allow_null' => 0,
                        'layout' => 'vertical',
                    ),
                    array(
                        'key' => 'field_687e71bc3199c',
                        'label' => 'Mobile',
                        'name' => 'mobile',
                        'aria-label' => '',
                        'type' => 'button_group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'wrap' => 'wrap',
                            'nowrap' => 'nowrap',
                        ),
                        'default_value' => 'wrap',
                        'return_format' => 'value',
                        'allow_null' => 0,
                        'layout' => 'vertical',
                    ),
                ),
            ),
            array(
                'key' => 'field_687e71bc3199d',
                'label' => 'Column Gap',
                'name' => 'column_gap',
                'aria-label' => '',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'table',
                'sub_fields' => array(
                    array(
                        'key' => 'field_687e71bc3199e',
                        'label' => 'Desktop',
                        'name' => 'desktop',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_687e71bc3199f',
                        'label' => 'Tablet',
                        'name' => 'tablet',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_687e71bc319a0',
                        'label' => 'Mobile',
                        'name' => 'mobile',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_687e71bc319a1',
                'label' => 'Row Gap',
                'name' => 'row_gap',
                'aria-label' => '',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'table',
                'sub_fields' => array(
                    array(
                        'key' => 'field_687e71bc319a2',
                        'label' => 'Desktop',
                        'name' => 'desktop',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_687e71bc319a3',
                        'label' => 'Tablet',
                        'name' => 'tablet',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_687e71bc319a4',
                        'label' => 'Mobile',
                        'name' => 'mobile',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_687e71bc319a5',
                'label' => 'Horizontal Alignment',
                'name' => 'horizontal_alignment',
                'aria-label' => '',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'table',
                'sub_fields' => array(
                    array(
                        'key' => 'field_687e71bc319a6',
                        'label' => 'Desktop',
                        'name' => 'desktop',
                        'aria-label' => '',
                        'type' => 'button_group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'flex-start' => 'Start',
                            'center' => 'Center',
                            'flex-end' => 'End',
                            'space-between' => 'Between',
                            'space-around' => 'Around',
                        ),
                        'default_value' => '',
                        'return_format' => 'value',
                        'allow_null' => 0,
                        'layout' => 'vertical',
                    ),
                    array(
                        'key' => 'field_687e71bc319a7',
                        'label' => 'Tablet',
                        'name' => 'tablet',
                        'aria-label' => '',
                        'type' => 'button_group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'flex-start' => 'Start',
                            'center' => 'Center',
                            'flex-end' => 'End',
                            'space-between' => 'Between',
                            'space-around' => 'Around',
                        ),
                        'default_value' => '',
                        'return_format' => 'value',
                        'allow_null' => 0,
                        'layout' => 'vertical',
                    ),
                    array(
                        'key' => 'field_687e71bc319a8',
                        'label' => 'Mobile',
                        'name' => 'mobile',
                        'aria-label' => '',
                        'type' => 'button_group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'flex-start' => 'Start',
                            'center' => 'Center',
                            'flex-end' => 'End',
                            'space-between' => 'Between',
                            'space-around' => 'Around',
                        ),
                        'default_value' => '',
                        'return_format' => 'value',
                        'allow_null' => 0,
                        'layout' => 'vertical',
                    ),
                ),
            ),
            array(
                'key' => 'field_687e71bc319a9',
                'label' => 'Vertical Alignment',
                'name' => 'vertical_alignment',
                'aria-label' => '',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'table',
                'sub_fields' => array(
                    array(
                        'key' => 'field_687e71bc319aa',
                        'label' => 'Desktop',
                        'name' => 'desktop',
                        'aria-label' => '',
                        'type' => 'button_group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'flex-start' => 'Start',
                            'center' => 'Center',
                            'flex-end' => 'End',
                            'stretch' => 'Stretch',
                        ),
                        'default_value' => '',
                        'return_format' => 'value',
                        'allow_null' => 0,
                        'layout' => 'vertical',
                    ),
                    array(
                        'key' => 'field_687e71bc319ab',
                        'label' => 'Tablet',
                        'name' => 'tablet',
                        'aria-label' => '',
                        'type' => 'button_group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'flex-start' => 'Start',
                            'center' => 'Center',
                            'flex-end' => 'End',
                            'stretch' => 'Stretch',
                        ),
                        'default_value' => '',
                        'return_format' => 'value',
                        'allow_null' => 0,
                        'layout' => 'vertical',
                    ),
                    array(
                        'key' => 'field_687e71bc319ac',
                        'label' => 'Mobile',
                        'name' => 'mobile',
                        'aria-label' => '',
                        'type' => 'button_group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'flex-start' => 'Start',
                            'center' => 'Center',
                            'flex-end' => 'End',
                            'stretch' => 'Stretch',
                        ),
                        'default_value' => '',
                        'return_format' => 'value',
                        'allow_null' => 0,
                        'layout' => 'vertical',
                    ),
                ),
            ),
            array(
                'key' => 'field_687e71bc319ad',
                'label' => 'Direction',
                'name' => 'direction',
                'aria-label' => '',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'table',
                'sub_fields' => array(
                    array(
                        'key' => 'field_687e71bc319ae',
                        'label' => 'Desktop',
                        'name' => 'desktop',
                        'aria-label' => '',
                        'type' => 'button_group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'row' => 'row',
                            'row-reverse' => 'row-reverse',
                            'column' => 'column',
                            'column-reverse' => 'column-reverse',
                        ),
                        'default_value' => 'row',
                        'return_format' => 'value',
                        'allow_null' => 0,
                        'layout' => 'vertical',
                    ),
                    array(
                        'key' => 'field_687e71bc319af',
                        'label' => 'Tablet',
                        'name' => 'tablet',
                        'aria-label' => '',
                        'type' => 'button_group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'row' => 'row',
                            'row-reverse' => 'row-reverse',
                            'column' => 'column',
                            'column-reverse' => 'column-reverse',
                        ),
                        'default_value' => 'row',
                        'return_format' => 'value',
                        'allow_null' => 0,
                        'layout' => 'vertical',
                    ),
                    array(
                        'key' => 'field_687e71bc319b0',
                        'label' => 'Mobile',
                        'name' => 'mobile',
                        'aria-label' => '',
                        'type' => 'button_group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'row' => 'row',
                            'row-reverse' => 'row-reverse',
                            'column' => 'column',
                            'column-reverse' => 'column-reverse',
                        ),
                        'default_value' => 'row',
                        'return_format' => 'value',
                        'allow_null' => 0,
                        'layout' => 'vertical',
                    ),
                ),
            ),
        ),
    );
}

