<?php

require_once plugin_dir_path(__FILE__) . 'rules/flex-alignment.php';
$flex_alignment = get_flex_alignment_rules();

require_once plugin_dir_path(__FILE__) . 'rules/typography.php';
$button_typography = get_typography_rules('Typography');
$button_typography_hover = get_typography_rules('Typography Hover');

require_once plugin_dir_path(__FILE__) . 'rules/background-color.php';
$button_background = get_bg_color_rules('Background');
$button_background_hover = get_bg_color_rules('Background Hover');

if ( ! function_exists( 'acf_add_local_field_group' ) ) {
    return;
}

acf_add_local_field_group( array(
    'key' => 'group_687de73dcb64c',
    'title' => 'Button Block Settings',
    'fields' => array(
        array(
            'key' => 'field_687de7644bbc2',
            'label' => 'Button Block Settings',
            'name' => 'button_block_settings',
            'aria-label' => '',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_687e05e5eef36',
                    'label' => 'Items Settings',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
                array(
                    'key' => 'field_687de7714bbc3',
                    'label' => 'Items',
                    'name' => 'items',
                    'aria-label' => '',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'collapsed' => '',
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'block',
                    'button_label' => 'Add Row',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_687df1944bc80',
                            'label' => 'Item',
                            'name' => '',
                            'aria-label' => '',
                            'type' => 'accordion',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'open' => 0,
                            'multi_expand' => 0,
                            'endpoint' => 0,
                            'parent_repeater' => 'field_687de7714bbc3',
                        ),
                        array(
                            'key' => 'field_687de7784bbc4',
                            'label' => 'Link',
                            'name' => 'link',
                            'aria-label' => '',
                            'type' => 'link',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                            'parent_repeater' => 'field_687de7714bbc3',
                        ),
                        array(
                            'key' => 'field_687e0b043c812',
                            'label' => 'Width',
                            'name' => 'width',
                            'aria-label' => '',
                            'type' => 'group',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'table',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_687e0d32f2aa0',
                                    'label' => 'Desktop',
                                    'name' => 'desktop',
                                    'aria-label' => '',
                                    'type' => 'group',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'layout' => 'block',
                                    'sub_fields' => array(
                                        array(
                                            'key' => 'field_687e0df0e9c4b',
                                            'label' => 'Min Width',
                                            'name' => 'min_width',
                                            'aria-label' => '',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'maxlength' => '',
                                        ),
                                        array(
                                            'key' => 'field_687e0df6e9c4c',
                                            'label' => 'Stretch',
                                            'name' => 'stretch',
                                            'aria-label' => '',
                                            'type' => 'true_false',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'message' => '',
                                            'default_value' => 0,
                                            'ui' => 0,
                                            'ui_on_text' => '',
                                            'ui_off_text' => '',
                                        ),
                                    ),
                                ),
                                array(
                                    'key' => 'field_687e0e17e9c4d',
                                    'label' => 'Tablet',
                                    'name' => 'tablet',
                                    'aria-label' => '',
                                    'type' => 'group',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'layout' => 'block',
                                    'sub_fields' => array(
                                        array(
                                            'key' => 'field_687e0e17e9c4e',
                                            'label' => 'Min Width',
                                            'name' => 'min_width',
                                            'aria-label' => '',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'maxlength' => '',
                                        ),
                                        array(
                                            'key' => 'field_687e0e17e9c4f',
                                            'label' => 'Stretch',
                                            'name' => 'stretch',
                                            'aria-label' => '',
                                            'type' => 'true_false',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'message' => '',
                                            'default_value' => 0,
                                            'ui' => 0,
                                            'ui_on_text' => '',
                                            'ui_off_text' => '',
                                        ),
                                    ),
                                ),
                                array(
                                    'key' => 'field_687e0e23e9c51',
                                    'label' => 'Mobile',
                                    'name' => 'mobile',
                                    'aria-label' => '',
                                    'type' => 'group',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'layout' => 'block',
                                    'sub_fields' => array(
                                        array(
                                            'key' => 'field_687e0e23e9c52',
                                            'label' => 'Min Width',
                                            'name' => 'min_width',
                                            'aria-label' => '',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'maxlength' => '',
                                        ),
                                        array(
                                            'key' => 'field_687e0e23e9c53',
                                            'label' => 'Stretch',
                                            'name' => 'stretch',
                                            'aria-label' => '',
                                            'type' => 'true_false',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'message' => '',
                                            'default_value' => 0,
                                            'ui' => 0,
                                            'ui_on_text' => '',
                                            'ui_off_text' => '',
                                        ),
                                    ),
                                ),
                            ),
                            'parent_repeater' => 'field_687de7714bbc3',
                        ),
                        array(
                            'key' => 'field_687e13a8428bc',
                            'label' => 'Initial State',
                            'name' => '',
                            'aria-label' => '',
                            'type' => 'tab',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'placement' => 'top',
                            'endpoint' => 0,
                            'parent_repeater' => 'field_687de7714bbc3',
                        ),
                        $button_background,
                        $button_typography,
                        array(
                            'key' => 'field_687deea13d26d',
                            'label' => 'Border',
                            'name' => 'border',
                            'aria-label' => '',
                            'type' => 'group',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'table',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_687deee03d26e',
                                    'label' => 'Width',
                                    'name' => 'width',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                array(
                                    'key' => 'field_687deee73d26f',
                                    'label' => 'Color',
                                    'name' => 'color',
                                    'aria-label' => '',
                                    'type' => 'color_picker',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'enable_opacity' => 0,
                                    'return_format' => 'string',
                                ),
                                array(
                                    'key' => 'field_687deeef3d270',
                                    'label' => 'Radius',
                                    'name' => 'radius',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                            ),
                            'parent_repeater' => 'field_687de7714bbc3',
                        ),
                        array(
                            'key' => 'field_687deef83d271',
                            'label' => 'Icon',
                            'name' => 'icon',
                            'aria-label' => '',
                            'type' => 'group',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'table',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_687def203d272',
                                    'label' => 'Image',
                                    'name' => 'image',
                                    'aria-label' => '',
                                    'type' => 'image',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'array',
                                    'preview_size' => 'thumbnail',
                                    'library' => 'all',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => '',
                                ),
                                array(
                                    'key' => 'field_687def2b3d273',
                                    'label' => 'Position',
                                    'name' => 'position',
                                    'aria-label' => '',
                                    'type' => 'button_group',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                        'icon-left' => 'left',
                                        'icon-right' => 'right',
                                    ),
                                    'allow_null' => 0,
                                    'default_value' => 'right',
                                    'layout' => 'vertical',
                                    'return_format' => 'value',
                                ),
                            ),
                            'parent_repeater' => 'field_687de7714bbc3',
                        ),
                        array(
                            'key' => 'field_687e125ecd7b6',
                            'label' => 'Hover State',
                            'name' => '',
                            'aria-label' => '',
                            'type' => 'tab',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'placement' => 'top',
                            'endpoint' => 0,
                            'parent_repeater' => 'field_687de7714bbc3',
                        ),
                        $button_background_hover,
                        $button_typography_hover,
                        array(
                            'key' => 'field_687e129ecd7b7',
                            'label' => 'Border (hover)',
                            'name' => 'border_hover',
                            'aria-label' => '',
                            'type' => 'group',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'table',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_687e129ecd7b8',
                                    'label' => 'Width',
                                    'name' => 'width',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                array(
                                    'key' => 'field_687e129ecd7b9',
                                    'label' => 'Color',
                                    'name' => 'color',
                                    'aria-label' => '',
                                    'type' => 'color_picker',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'enable_opacity' => 0,
                                    'return_format' => 'string',
                                ),
                                array(
                                    'key' => 'field_687e129ecd7ba',
                                    'label' => 'Radius',
                                    'name' => 'radius',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                            ),
                            'parent_repeater' => 'field_687de7714bbc3',
                        ),
                    ),
                    'rows_per_page' => 20,
                ),
                array(
                    'key' => 'field_687e05fbeef37',
                    'label' => 'Alignment Settings Tab',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
                $flex_alignment,
            ),
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/vs-button-block',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
) );


