<?php

require_once plugin_dir_path(__FILE__) . 'rules/flex-alignment.php';
$flex_alignment = get_flex_alignment_rules();


if ( ! function_exists( 'acf_add_local_field_group' ) ) {
    return;
}

acf_add_local_field_group( array(
    'key' => 'group_687932b5bd912',
    'title' => 'Image Block Settings',
    'fields' => array(
        array(
            'key' => 'field_687932cca5f0c',
            'label' => 'Image Block Settings',
            'name' => 'image_block_settings',
            'aria-label' => '',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_68793d180dda4',
                    'label' => 'Images Settings',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
                array(
                    'key' => 'field_687937977fc04',
                    'label' => 'Images',
                    'name' => 'images',
                    'aria-label' => '',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'collapsed' => '',
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'block',
                    'button_label' => 'Add Row',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_6879385c50028',
                            'label' => 'Image',
                            'name' => '',
                            'aria-label' => '',
                            'type' => 'accordion',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'open' => 0,
                            'multi_expand' => 0,
                            'endpoint' => 0,
                            'parent_repeater' => 'field_687937977fc04',
                        ),
                        array(
                            'key' => 'field_687937a27fc05',
                            'label' => 'Image Desktop',
                            'name' => 'image_desktop',
                            'aria-label' => '',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                            'parent_repeater' => 'field_687937977fc04',
                        ),
                        array(
                            'key' => 'field_6879f24a773c5',
                            'label' => 'Image Mobile',
                            'name' => 'image_mobile',
                            'aria-label' => '',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                            'parent_repeater' => 'field_687937977fc04',
                        ),
                        array(
                            'key' => 'field_687932f7a5f0e',
                            'label' => 'Width',
                            'name' => 'width',
                            'aria-label' => '',
                            'type' => 'group',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'table',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_687932fea5f0f',
                                    'label' => 'Desktop',
                                    'name' => 'desktop',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                array(
                                    'key' => 'field_68793305a5f10',
                                    'label' => 'Tablet',
                                    'name' => 'tablet',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                array(
                                    'key' => 'field_68793309a5f11',
                                    'label' => 'Mobile',
                                    'name' => 'mobile',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                            ),
                            'parent_repeater' => 'field_687937977fc04',
                        ),
                        array(
                            'key' => 'field_68793311a5f12',
                            'label' => 'Height',
                            'name' => 'height',
                            'aria-label' => '',
                            'type' => 'group',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'table',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_68793311a5f13',
                                    'label' => 'Desktop',
                                    'name' => 'desktop',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                array(
                                    'key' => 'field_68793311a5f14',
                                    'label' => 'Tablet',
                                    'name' => 'tablet',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                array(
                                    'key' => 'field_68793311a5f15',
                                    'label' => 'Mobile',
                                    'name' => 'mobile',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                            ),
                            'parent_repeater' => 'field_687937977fc04',
                        ),
                        array(
                            'key' => 'field_6879331ca5f16',
                            'label' => 'Object Fit',
                            'name' => 'object_fit',
                            'aria-label' => '',
                            'type' => 'button_group',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'vs-image-cover' => 'cover',
                                'vs-image-contain' => 'contain',
                            ),
                            'allow_null' => 0,
                            'default_value' => 'vs-image-contain',
                            'layout' => 'horizontal',
                            'return_format' => 'value',
                            'parent_repeater' => 'field_687937977fc04',
                        ),
                        array(
                            'key' => 'field_6879fd47c959e',
                            'label' => 'Border',
                            'name' => 'border',
                            'aria-label' => '',
                            'type' => 'group',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'table',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_6879fd53c959f',
                                    'label' => 'Color',
                                    'name' => 'color',
                                    'aria-label' => '',
                                    'type' => 'color_picker',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'enable_opacity' => 0,
                                    'return_format' => 'string',
                                ),
                                array(
                                    'key' => 'field_6879fd5ec95a0',
                                    'label' => 'Width',
                                    'name' => 'width',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                array(
                                    'key' => 'field_6879fd64c95a1',
                                    'label' => 'Style',
                                    'name' => 'style',
                                    'aria-label' => '',
                                    'type' => 'select',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                        'none' => 'none',
                                        'dotted' => 'dotted',
                                        'dashed' => 'dashed',
                                        'solid' => 'solid',
                                        'double' => 'double',
                                        'groove' => 'groove',
                                        'ridge' => 'ridge',
                                        'inset' => 'inset',
                                        'outset' => 'outset',
                                    ),
                                    'default_value' => 'none',
                                    'allow_null' => 0,
                                    'multiple' => 0,
                                    'ui' => 0,
                                    'return_format' => 'value',
                                    'ajax' => 0,
                                    'placeholder' => '',
                                ),
                                array(
                                    'key' => 'field_6879fd6ac95a2',
                                    'label' => 'Radius',
                                    'name' => 'radius',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                            ),
                            'parent_repeater' => 'field_687937977fc04',
                        ),
                    ),
                    'rows_per_page' => 20,
                ),
                array(
                    'key' => 'field_68793d230dda5',
                    'label' => 'Alignment Settings',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
                $flex_alignment
//                    array(
//                        'key' => 'field_68793c63e5d92',
//                        'label' => 'Flex Settings',
//                        'name' => 'flex_settings',
//                        'aria-label' => '',
//                        'type' => 'group',
//                        'instructions' => '',
//                        'required' => 0,
//                        'conditional_logic' => 0,
//                        'wrapper' => array(
//                            'width' => '',
//                            'class' => '',
//                            'id' => '',
//                        ),
//                        'layout' => 'block',
//                        'sub_fields' => array(
//                            array(
//                                'key' => 'field_68793c7be5d93',
//                                'label' => 'Wrap',
//                                'name' => 'wrap',
//                                'aria-label' => '',
//                                'type' => 'group',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'layout' => 'block',
//                                'sub_fields' => array(
//                                    array(
//                                        'key' => 'field_68793c97e5d94',
//                                        'label' => 'Desktop',
//                                        'name' => 'desktop',
//                                        'aria-label' => '',
//                                        'type' => 'button_group',
//                                        'instructions' => '',
//                                        'required' => 0,
//                                        'conditional_logic' => 0,
//                                        'wrapper' => array(
//                                            'width' => '',
//                                            'class' => '',
//                                            'id' => '',
//                                        ),
//                                        'choices' => array(
//                                            'wrap' => 'wrap',
//                                            'nowrap' => 'nowrap',
//                                        ),
//                                        'allow_null' => 0,
//                                        'default_value' => 'wrap',
//                                        'layout' => 'vertical',
//                                        'return_format' => 'value',
//                                    ),
//                                    array(
//                                        'key' => 'field_6879ebbf3e445',
//                                        'label' => 'Tablet',
//                                        'name' => 'tablet',
//                                        'aria-label' => '',
//                                        'type' => 'button_group',
//                                        'instructions' => '',
//                                        'required' => 0,
//                                        'conditional_logic' => 0,
//                                        'wrapper' => array(
//                                            'width' => '',
//                                            'class' => '',
//                                            'id' => '',
//                                        ),
//                                        'choices' => array(
//                                            'wrap' => 'wrap',
//                                            'nowrap' => 'nowrap',
//                                        ),
//                                        'allow_null' => 0,
//                                        'default_value' => 'wrap',
//                                        'layout' => 'vertical',
//                                        'return_format' => 'value',
//                                    ),
//                                    array(
//                                        'key' => 'field_6879ebbe3e444',
//                                        'label' => 'Mobile',
//                                        'name' => 'mobile',
//                                        'aria-label' => '',
//                                        'type' => 'button_group',
//                                        'instructions' => '',
//                                        'required' => 0,
//                                        'conditional_logic' => 0,
//                                        'wrapper' => array(
//                                            'width' => '',
//                                            'class' => '',
//                                            'id' => '',
//                                        ),
//                                        'choices' => array(
//                                            'wrap' => 'wrap',
//                                            'nowrap' => 'nowrap',
//                                        ),
//                                        'allow_null' => 0,
//                                        'default_value' => 'wrap',
//                                        'layout' => 'vertical',
//                                        'return_format' => 'value',
//                                    ),
//                                ),
//                            ),
//                            array(
//                                'key' => 'field_68793cd3e5d97',
//                                'label' => 'Column Gap',
//                                'name' => 'column_gap',
//                                'aria-label' => '',
//                                'type' => 'group',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'layout' => 'table',
//                                'sub_fields' => array(
//                                    array(
//                                        'key' => 'field_68793cdde5d98',
//                                        'label' => 'Desktop',
//                                        'name' => 'desktop',
//                                        'aria-label' => '',
//                                        'type' => 'text',
//                                        'instructions' => '',
//                                        'required' => 0,
//                                        'conditional_logic' => 0,
//                                        'wrapper' => array(
//                                            'width' => '',
//                                            'class' => '',
//                                            'id' => '',
//                                        ),
//                                        'default_value' => '',
//                                        'placeholder' => '',
//                                        'prepend' => '',
//                                        'append' => '',
//                                        'maxlength' => '',
//                                    ),
//                                    array(
//                                        'key' => 'field_68793ce3e5d99',
//                                        'label' => 'Tablet',
//                                        'name' => 'tablet',
//                                        'aria-label' => '',
//                                        'type' => 'text',
//                                        'instructions' => '',
//                                        'required' => 0,
//                                        'conditional_logic' => 0,
//                                        'wrapper' => array(
//                                            'width' => '',
//                                            'class' => '',
//                                            'id' => '',
//                                        ),
//                                        'default_value' => '',
//                                        'placeholder' => '',
//                                        'prepend' => '',
//                                        'append' => '',
//                                        'maxlength' => '',
//                                    ),
//                                    array(
//                                        'key' => 'field_68793ce8e5d9a',
//                                        'label' => 'Mobile',
//                                        'name' => 'mobile',
//                                        'aria-label' => '',
//                                        'type' => 'text',
//                                        'instructions' => '',
//                                        'required' => 0,
//                                        'conditional_logic' => 0,
//                                        'wrapper' => array(
//                                            'width' => '',
//                                            'class' => '',
//                                            'id' => '',
//                                        ),
//                                        'default_value' => '',
//                                        'placeholder' => '',
//                                        'prepend' => '',
//                                        'append' => '',
//                                        'maxlength' => '',
//                                    ),
//                                ),
//                            ),
//                            array(
//                                'key' => 'field_6879f0a5982d7',
//                                'label' => 'Row Gap',
//                                'name' => 'row_gap',
//                                'aria-label' => '',
//                                'type' => 'group',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'layout' => 'table',
//                                'sub_fields' => array(
//                                    array(
//                                        'key' => 'field_6879f0a5982d8',
//                                        'label' => 'Desktop',
//                                        'name' => 'desktop',
//                                        'aria-label' => '',
//                                        'type' => 'text',
//                                        'instructions' => '',
//                                        'required' => 0,
//                                        'conditional_logic' => 0,
//                                        'wrapper' => array(
//                                            'width' => '',
//                                            'class' => '',
//                                            'id' => '',
//                                        ),
//                                        'default_value' => '',
//                                        'placeholder' => '',
//                                        'prepend' => '',
//                                        'append' => '',
//                                        'maxlength' => '',
//                                    ),
//                                    array(
//                                        'key' => 'field_6879f0a5982d9',
//                                        'label' => 'Tablet',
//                                        'name' => 'tablet',
//                                        'aria-label' => '',
//                                        'type' => 'text',
//                                        'instructions' => '',
//                                        'required' => 0,
//                                        'conditional_logic' => 0,
//                                        'wrapper' => array(
//                                            'width' => '',
//                                            'class' => '',
//                                            'id' => '',
//                                        ),
//                                        'default_value' => '',
//                                        'placeholder' => '',
//                                        'prepend' => '',
//                                        'append' => '',
//                                        'maxlength' => '',
//                                    ),
//                                    array(
//                                        'key' => 'field_6879f0a5982da',
//                                        'label' => 'Mobile',
//                                        'name' => 'mobile',
//                                        'aria-label' => '',
//                                        'type' => 'text',
//                                        'instructions' => '',
//                                        'required' => 0,
//                                        'conditional_logic' => 0,
//                                        'wrapper' => array(
//                                            'width' => '',
//                                            'class' => '',
//                                            'id' => '',
//                                        ),
//                                        'default_value' => '',
//                                        'placeholder' => '',
//                                        'prepend' => '',
//                                        'append' => '',
//                                        'maxlength' => '',
//                                    ),
//                                ),
//                            ),
//                            array(
//                                'key' => 'field_6879ff0749b1d',
//                                'label' => 'Horizontal Alignment',
//                                'name' => 'horizontal_alignment',
//                                'aria-label' => '',
//                                'type' => 'group',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'layout' => 'table',
//                                'sub_fields' => array(
//                                    array(
//                                        'key' => 'field_6879ff1849b1e',
//                                        'label' => 'Desktop',
//                                        'name' => 'desktop',
//                                        'aria-label' => '',
//                                        'type' => 'button_group',
//                                        'instructions' => '',
//                                        'required' => 0,
//                                        'conditional_logic' => 0,
//                                        'wrapper' => array(
//                                            'width' => '',
//                                            'class' => '',
//                                            'id' => '',
//                                        ),
//                                        'choices' => array(
//                                            'flex-start' => 'Start',
//                                            'center' => 'Center',
//                                            'flex-end' => 'End',
//                                            'space-between' => 'Between',
//                                            'space-around' => 'Around',
//                                        ),
//                                        'allow_null' => 0,
//                                        'default_value' => '',
//                                        'layout' => 'vertical',
//                                        'return_format' => 'value',
//                                    ),
//                                    array(
//                                        'key' => 'field_6879ff7649b20',
//                                        'label' => 'Tablet',
//                                        'name' => 'tablet',
//                                        'aria-label' => '',
//                                        'type' => 'button_group',
//                                        'instructions' => '',
//                                        'required' => 0,
//                                        'conditional_logic' => 0,
//                                        'wrapper' => array(
//                                            'width' => '',
//                                            'class' => '',
//                                            'id' => '',
//                                        ),
//                                        'choices' => array(
//                                            'flex-start' => 'Start',
//                                            'center' => 'Center',
//                                            'flex-end' => 'End',
//                                            'space-between' => 'Between',
//                                            'space-around' => 'Around',
//                                        ),
//                                        'allow_null' => 0,
//                                        'default_value' => '',
//                                        'layout' => 'vertical',
//                                        'return_format' => 'value',
//                                    ),
//                                    array(
//                                        'key' => 'field_6879ff7e49b21',
//                                        'label' => 'Mobile',
//                                        'name' => 'mobile',
//                                        'aria-label' => '',
//                                        'type' => 'button_group',
//                                        'instructions' => '',
//                                        'required' => 0,
//                                        'conditional_logic' => 0,
//                                        'wrapper' => array(
//                                            'width' => '',
//                                            'class' => '',
//                                            'id' => '',
//                                        ),
//                                        'choices' => array(
//                                            'flex-start' => 'Start',
//                                            'center' => 'Center',
//                                            'flex-end' => 'End',
//                                            'space-between' => 'Between',
//                                            'space-around' => 'Around',
//                                        ),
//                                        'allow_null' => 0,
//                                        'default_value' => '',
//                                        'layout' => 'vertical',
//                                        'return_format' => 'value',
//                                    ),
//                                ),
//                            ),
//                            array(
//                                'key' => 'field_6879ffa449b22',
//                                'label' => 'Vertical Alignment',
//                                'name' => 'vertical_alignment',
//                                'aria-label' => '',
//                                'type' => 'group',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'layout' => 'table',
//                                'sub_fields' => array(
//                                    array(
//                                        'key' => 'field_6879ffa449b23',
//                                        'label' => 'Desktop',
//                                        'name' => 'desktop',
//                                        'aria-label' => '',
//                                        'type' => 'button_group',
//                                        'instructions' => '',
//                                        'required' => 0,
//                                        'conditional_logic' => 0,
//                                        'wrapper' => array(
//                                            'width' => '',
//                                            'class' => '',
//                                            'id' => '',
//                                        ),
//                                        'choices' => array(
//                                            'flex-start' => 'Start',
//                                            'center' => 'Center',
//                                            'flex-end' => 'End',
//                                            'stretch' => 'Stretch',
//                                        ),
//                                        'allow_null' => 0,
//                                        'default_value' => '',
//                                        'layout' => 'vertical',
//                                        'return_format' => 'value',
//                                    ),
//                                    array(
//                                        'key' => 'field_6879ffa449b24',
//                                        'label' => 'Tablet',
//                                        'name' => 'tablet',
//                                        'aria-label' => '',
//                                        'type' => 'button_group',
//                                        'instructions' => '',
//                                        'required' => 0,
//                                        'conditional_logic' => 0,
//                                        'wrapper' => array(
//                                            'width' => '',
//                                            'class' => '',
//                                            'id' => '',
//                                        ),
//                                        'choices' => array(
//                                            'flex-start' => 'Start',
//                                            'center' => 'Center',
//                                            'flex-end' => 'End',
//                                            'stretch' => 'Stretch',
//                                        ),
//                                        'allow_null' => 0,
//                                        'default_value' => '',
//                                        'layout' => 'vertical',
//                                        'return_format' => 'value',
//                                    ),
//                                    array(
//                                        'key' => 'field_6879ffa449b25',
//                                        'label' => 'Mobile',
//                                        'name' => 'mobile',
//                                        'aria-label' => '',
//                                        'type' => 'button_group',
//                                        'instructions' => '',
//                                        'required' => 0,
//                                        'conditional_logic' => 0,
//                                        'wrapper' => array(
//                                            'width' => '',
//                                            'class' => '',
//                                            'id' => '',
//                                        ),
//                                        'choices' => array(
//                                            'flex-start' => 'Start',
//                                            'center' => 'Center',
//                                            'flex-end' => 'End',
//                                            'stretch' => 'Stretch',
//                                        ),
//                                        'allow_null' => 0,
//                                        'default_value' => '',
//                                        'layout' => 'vertical',
//                                        'return_format' => 'value',
//                                    ),
//                                ),
//                            ),
//                            array(
//                                'key' => 'field_687a043c2bf16',
//                                'label' => 'Direction',
//                                'name' => 'direction',
//                                'aria-label' => '',
//                                'type' => 'group',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'layout' => 'table',
//                                'sub_fields' => array(
//                                    array(
//                                        'key' => 'field_687a04462bf17',
//                                        'label' => 'Desktop',
//                                        'name' => 'desktop',
//                                        'aria-label' => '',
//                                        'type' => 'button_group',
//                                        'instructions' => '',
//                                        'required' => 0,
//                                        'conditional_logic' => 0,
//                                        'wrapper' => array(
//                                            'width' => '',
//                                            'class' => '',
//                                            'id' => '',
//                                        ),
//                                        'choices' => array(
//                                            'row' => 'row',
//                                            'row-reverse' => 'row-reverse',
//                                            'column' => 'column',
//                                            'column-reverse' => 'column-reverse',
//                                        ),
//                                        'allow_null' => 0,
//                                        'default_value' => 'row',
//                                        'layout' => 'vertical',
//                                        'return_format' => 'value',
//                                    ),
//                                    array(
//                                        'key' => 'field_687a04672bf18',
//                                        'label' => 'Tablet',
//                                        'name' => 'tablet',
//                                        'aria-label' => '',
//                                        'type' => 'button_group',
//                                        'instructions' => '',
//                                        'required' => 0,
//                                        'conditional_logic' => 0,
//                                        'wrapper' => array(
//                                            'width' => '',
//                                            'class' => '',
//                                            'id' => '',
//                                        ),
//                                        'choices' => array(
//                                            'row' => 'row',
//                                            'row-reverse' => 'row-reverse',
//                                            'column' => 'column',
//                                            'column-reverse' => 'column-reverse',
//                                        ),
//                                        'allow_null' => 0,
//                                        'default_value' => 'row',
//                                        'layout' => 'vertical',
//                                        'return_format' => 'value',
//                                    ),
//                                    array(
//                                        'key' => 'field_687a04762bf1a',
//                                        'label' => 'Mobile',
//                                        'name' => 'mobile',
//                                        'aria-label' => '',
//                                        'type' => 'button_group',
//                                        'instructions' => '',
//                                        'required' => 0,
//                                        'conditional_logic' => 0,
//                                        'wrapper' => array(
//                                            'width' => '',
//                                            'class' => '',
//                                            'id' => '',
//                                        ),
//                                        'choices' => array(
//                                            'row' => 'row',
//                                            'row-reverse' => 'row-reverse',
//                                            'column' => 'column',
//                                            'column-reverse' => 'column-reverse',
//                                        ),
//                                        'allow_null' => 0,
//                                        'default_value' => 'row',
//                                        'layout' => 'vertical',
//                                        'return_format' => 'value',
//                                    ),
//                                ),
//                            ),
//                        ),
//                    ),
            ),
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/vs-image-block',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
) );


